[package]
name = "ecr-image-browser"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
structopt = "0.3.26"
aws-config = "1.5.4"
aws-sdk-ecr = "1.37.0"
inquire = "0.7.5"
ini = "1.3.0"
shellexpand = "3.1.0"
aws-smithy-http = "0.60.9"